apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: words
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: words
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
