apiVersion: v1
kind: Service
metadata:
  name: max-object-detector
spec:
  selector:
    app: max-object-detector
  ports:
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: max-object-detector
  labels:
    app: max-object-detector
spec:
  selector:
    matchLabels:
      app: max-object-detector
  replicas: 2
  template:
    metadata:
      labels:
        app: max-object-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - west
      containers:
      - name: max-object-detector
        image: quay.io/codait/max-object-detector:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
        #name: basic-kubernetes-dns
  #spec:
        #rules:
          # - host: 34.133.234.180.nip.io
    # http:
    # paths:
              # - path: /
        #pathType: ImplementationSpecific
        #       backend:
                #  service:
                  #name: max-object-detector
            # port:
                    #   number: 5000

